name: Node.js CD
 
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: master
          check-name: build
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DISCORD_PLAY_FMI_PPK }}
          script: |
            BRAWLHALLA_API_TOKEN=${{ secrets.BRAWLHALLA_API_TOKEN }}
            DISCORD_API_TOKENL=${{ secrets.DISCORD_API_TOKEN }}
            cd brawlball_ranked
            git pull
            npm install
            npm run build --if-present
            screen -md -S 'brawlball_ranked' npm start