name: Deploy Node.js Application
 
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DISCORD_PLAY_FMI_PPK }}
          envs:
            BRAWLHALLA_API_TOKEN: ${{ secrets.BRAWLHALLA_API_TOKEN }}
            DISCORD_API_TOKENL: ${{ secrets.DISCORD_API_TOKEN }}
          script: |
            cd brawlball_ranked
            git pull
            npm install
            npm run build --if-present
            screen -md -S 'brawlball_ranked' npm start